---
Name: cookieconsent
---
Innoweb\CookieConsent\CookieConsent:
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
  global_privacy_control: true
  opt_in:
    - AD
    - AT
    - BE
    - BG
    - BR
    - CA
    - CH
    - CN
    - CY
    - CZ
    - DE
    - DK
    - EE
    - ES
    - FI
    - FR
    - GB
    - GR
    - HR
    - HU
    - IE
    - IN
    - IS
    - IT
    - JP
    - KR
    - LI
    - LT
    - LU
    - LV
    - MC
    - MT
    - MX
    - NL
    - NO
    - PL
    - PT
    - RO
    - SE
    - SG
    - SI
    - SK
    - SM
    - TH
    - TR
    - VA
    - ZA
  opt_out: false
  do_not_sell:
    - US

SilverStripe\Control\Director:
  rules:
    acceptAllCookies: PageController

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Innoweb\CookieConsent\Extensions\ContentControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\CookieConsent\Extensions\SiteConfigExtension

---
Name: cookieconsent-cookie
After: cookie
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Cookie_Backend: Innoweb\CookieConsent\Control\CookieJar
